export const CREATE_PROJECT = 'CREATE_PROJECT';
export const PROJECT_CREATED = 'PROJECT_CREATED';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_DELETED = 'PROJECT_DELETED';

export const RUN_PROJECT = 'RUN_PROJECT';
export const PROJECT_RAN = 'PROJECT_RAN';

export const START_PROJECT = 'START_PROJECT';
export const PROJECT_STARTED = 'PROJECT_STARTED';

export const STOP_PROJECT = 'STOP_PROJECT';
export const PROJECT_STOPPED = 'PROJECT_STOPPED';

export const GET_PROJECT_STATS = 'GET_PROJECT_STATS';
export const PROJECT_GOT_STATS = 'PROJECT_GOT_STATS';

export const GET_PROJECT_RUNNING = 'GET_PROJECT_RUNNING';
export const PROJECT_GOT_RUNNING = 'PROJECT_GOT_RUNNING';
